sudo: false
language: node_js
node_js:
  - '12'
branches:
  only:
    - master
cache:
  directories:
    - node_modules
before_install:
  - npm prune
install:
  - npm install
script:
  - npm run build
deploy:
  - npm run deploy
