sudo: false
language: node_js
node_js:
  - '12'
branches:
  only:
    - master
cache:
  directories:
    - node_modules
before_install:
  - npm prune
install:
  - npm install
script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  keep_history: false
  local_dir: public
  repo: known-as-bmf/known-as-bmf.github.io
  target_branch: master
  on:
    branch: master
